site_name: ML Notes
site_url: https://2t2c.github.io/ml-notes/
theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - content.tooltips
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: pink
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode


markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - tables
  - pymdownx.magiclink
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - table-reader

nav:
  - 'Home': 
    - 'About': 'index.md'
  - 'Linear Algebra':
    - 'About': 'linear-algebra/about.md'
    - 'Chapters': 
      - 'Introduction to Vectors':
        - 'Preface': 'linear-algebra/introduction-to-vectors/preface.md'
        - 'Vectors and Linear Combinations': 'linear-algebra/introduction-to-vectors/vectors-and-linear-combinations.md'
        - 'Planes': 'linear-algebra/introduction-to-vectors/planes.md'
        - 'Lengths and Dot Products': 'linear-algebra/introduction-to-vectors/lengths-and-dot-products.md'
        - 'Matrices': 'linear-algebra/introduction-to-vectors/matrices.md'
      - 'Solving Linear Equations':
        - 'Preface': 'linear-algebra/solving-linear-equations/preface.md'
        - 'Methods': 'linear-algebra/solving-linear-equations/methods.md'
  - 'Machine Learning':
    - 'About': 'ml/about.md'
  - 'Reinforcement Learning':
    - 'About': 'rl/about.md'
  - 'Natural Language Processing':
    - 'About': 'nlp/about.md'
  - 'Computer Vision':
    - 'About': 'cv/about.md'
