site_name: ML Notes
theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.sections
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: pink
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  
nav:
  - 'Home': 
    - 'About': 'home/about.md'
  - 'Machine Learning':
    - 'About': 'ml/about.md'
  - 'Reinforcement Learning':
    - 'About': 'rl/about.md'
  - 'Natural Language Processing':
    - 'About': 'nlp/about.md'
  - 'Computer Vision':
    - 'About': 'cv/about.md'
